baseurl = "https://www.experimentinart.com" # Hostname (and path) to the root.
title = "Experiment In Art" # Site title.
theme = "coder-portfolio" # Set the theme.
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

disqusShortname = "yourdiscussshortname" # Enable or disable Disqus.

[params] # theme parameters
    author = "" # Author's name.
    info = "Experiment In Art" # Author's job title or info.
    description = "Blog by Will Bidstrup about art and science" # Site description.
    keywords = "blog,personal" # Site keywords.
    avatarurl = "images/eia_small.png" # Contain the path of the optionnal avatar in the static folder.

    footercontent = "Enter a text here." # Add footer content

   # Add fixedbar content after click

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

   

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.


# Menu links
[[menu.main]]
    name = "Thoughts"
    weight = 1
    url  = "/post/"
[[menu.main]]
    name = "About"
    weight = 3
    url = "/about/"
[[menu.main]]
    name = "Things"
    weight = 2
    url = "/things/"
[[menu.main]]
    name = "Tags"
    weight = 4
    url = "/tags/"