---
title: How thinking like a games developer can take data transformation to the next
  level
author: Will Bidstrup
date: '2020-04-27'
slug: how-thinking-like-a-games-developer-can-take-data-transformation-to-the-next-level
categories: []
tags:
  - data
description: ''
thumbnail: <no value>
---

*This article first appeared in [Consultancy Asia](https://www.consultancy.asia/news/3170/how-thinking-like-a-games-developer-can-take-data-transformation-to-the-next-level)*  

Modern organisations must move from being reactive to proactive with the handling of their data assets, and use those assets in service of their customers. Easy to say and yet harder to do, and we all benefit from casting a wide net to inspire our own learning through doing.  

In Asia, we have the most gaming-savvy population in the world. We were raised on Nintendo, we watch e-sports and play online more than anywhere else on the planet. What does this have to do with data management and digital business transformation? It means already high expectations on ‘what data can do’ – driven by the competitive landscape – are raised even higher, both for consumers and in boardrooms. 

These expectations are formed in part from simple, and seemingly reasonable questions; If it can happen in my interactions with a game, why not in real life? Why is my gaming software updated regularly, and my community managed well, while my bank, car dealership or gym struggles to even identify me as an existing customer? Where is the fun?  

While we have seen the video games industry move quickly from challenger to world domination, it is not immune to the winds of change and will face challenges in retaining its workforce, a potential mid-term decline in discretionary spending (following the short-term boost being experienced now) and a continuing flood of products in an incredibly competitive global market.  

So, organisations need to manage their data more effectively to stay competitive, expectations on what is possible and desirable are formed in part by our exposure to entertainment products, and the industry that creates many of these expectations is about to go through its own metamorphosis. Consultancies and non-gaming organisations can leverage this situation in a few ways.  

Firstly, we can borrow from the concept of ‘game engines’ in the selection of our technology. To bring a completed game into the world, game developers must set up an architecture and toolset from day one which allows them to prototype, test and ultimately deploy, first to dozens, then hundreds, thousands or maybe millions of players. Careful selection of pre-built and bespoke components is required to balance flexibility and speed with security, privacy and dependability.  

Secondly, we can use experiment design and information flow management to measure and then maximise the meaningful decision-making opportunities we offer to our ‘players’. Games are human-in-loop systems worth serious study. It’s common to equate decision making in game development to the AI systems which act to provide challenge to the human player.
While this is important, it is just one part of a portfolio of techniques which can be employed to increase player engagement. We all want to remove tedium and waste from our processes. Logically, what remains when a process is truly optimised, are meaningful decisions which need to be made by a human. Give your customers and staff choices with defined ranges of consequences. Provide data to inform the choices.  

Thirdly, we can look to bring world-class entertaining and informative analytics to bear on both internal *and* external customers. Gaming analytics began as typical monitoring of workloads and has evolved into sophisticated data capture of almost every conceivable event which can be analysed and used to inform all aspects of game design and development. This is particularly the case with regards to concepts such as ‘balance’ in competitive multiplayer games. These could be referred to as ‘functional analytics’.
The technology barriers to capturing significant event streams of data are reducing, along with the valid excuses to not experiment in this area. As well, we are seeing the increase of analytics being served up to players surrounding their interactions with games, increasing the fun factor and the scope of the experience with a game. This is ‘analytics as content’. Spoiler alert: e-sports analytics will drive innovation for personalised analytics at scale.  

Finally, a word on the most important element of any data or transformation team: the people who create the tools, manage the processes and make the meaningful decisions.
Unfortunately, this is one area where the video gaming industry does not reach a high score. What was widely suspected has more recently become widely reported – it appears game development teams are often not treated as well as their corporate cousins, facing brutal cycles of ‘crunch’. In a market where data and tech skills are in short supply and come at a premium, non-gaming organisations should consider how they can attract and retain the kinds of people who work at gaming companies – in many cases the bar to be exceeded does not seem too high and the benefits of bringing on skilled, multi-disciplinary techies with data literacy, customer obsession and creativity will be too good to ignore.  

Organisations stand to accelerate their own transformation by embracing the data tools, processes and people used by the experts in interactive entertainment. Game on!