---
title: How I Deliver My Daily Words
author: Will Bidstrup
date: '2019-01-08'
slug: how-i-deliver-my-daily-words
categories:
  - thoughts
tags:
  - writing
---

>“Words are to writers as clay is to sculptors.”  
> ― **(Old Jungle Saying)**  


Each morning I wrestle with my computer for exactly ten minutes and crank out some sentences. I have learned that I can deliver around 500 words in this timeframe. This is seemingly the maximum output my brain and two-finger clawhammer typing technique can muster. For now.  

I have been writing for many years in a sporadic fashion including publishing a few short stories and more than a few songs. But the true discipline and rigour of being a writer has eluded me. I created this routine to make daily writing a real part of who I am.  I started this particular approach sometime in late 2017 and it took a while to really sink in. Today I am at 65 consecutive days which I believe is a record for me. The habit is forming.  

I am aware writing every day is not a new idea, this is simply what works for me.  


# What I do

A ten minute uninterrupted writing session. No stopping. No thinking. Just writing. It is the first thing I do each day.  

# Why you should try it

**Start the day with positive energy.** You have just done something. 
Heal and strengthen your mind. If you are like me you may occasionally trawl the internet or come across content such as this which means you are interested in self-improvement or writing. You may have some difficulties in your life which you deal with through artistic expression. Get those toxic thoughts out onto paper or screen and expose them for what they are.  

**Build momentum.** 500 words a day is 182,500 words a year. That is a draft of a novel. Now, I know what you’re saying - no-one wants to read a novel about my self-obsessed stream-of-consciousness and that might be true. But what about the content in the next 10 minutes you spend after you’ve cleared your brain? 

# How to do it

**Obey the clock.** Personally I recommend the [Flowstate](http://hailoverman.com/flowstate) app. It will not tolerate laziness and a result is certain. Any break in typing for more than a few seconds during a 10 minute interval results in the total destruction of the entire document, with no chance of recovery. This threat alone is enough to keep me clacking away furiously. I can imagine other ways to keep the time dimension in frame - an appropriately sized sand-timer with occult engravings comes to mind. Whatever it is is, the key is to force yourself to keep going.  

**Ignore the quality of your writing.** Really. The inner critic causes writers block. You know, when you write a sentence and it’s terrible and so you delete it? Don’t do this. The point is that words are written, and with the bad ones out of the way, the good ones can shyly approach.  

**Make it a ritual.** I have devised a workflow to easily store, track and report these daily events. This gives me a good sense of progress and accomplishment. I'll write more about this another time.    

With the habit formed I look forward to these first minutes of the day.  

I wish you luck in devising your own routines and rituals to achieve daily writing.  