---
title: 5 Things Data Science Teams Can Learn From Creative Teams
author: Will Bidstrup
date: '2020-04-14'
slug: 5-things-data-science-teams-can-learn-from-creative-teams
categories: []
tags:
  - data
description: ''
thumbnail: <no value>
---


Many data science teams struggle to solve problems that have not been well defined. They are often left to their own devices to sift through information until they strike gold, or else are subject to an ever-evolving string of ‘requirements’ which generally focus on what and how, ignoring why and for who. Additionally, they may struggle to set up, structure and ultimately sell their solution to an audience of mixed experience.  
To address these challenges, I believe data science teams can learn a few tricks from classic advertising creative teams, who have been in the business of experimenting, solving problems, and winning others to their way of thinking for some time.   
￼
1. Ask for a brief, then focus on it.  
Wait a minute, what brief? Exactly. Creative teams are usually trained to demand a brief and then treat it like a sacred document. With some tweaking, a decent creative brief template will work for technical work where experimentation is required. Ask for one, or write one yourself and send it as an example of what you need, it’s usually easier for someone to change or add something than write from scratch. If you go this route be warned - brief writing is hard.  
But you’d better work to the brief. Do not demand a brief and then ignore it - that will significantly increase your risk of a brief-less future, spent wallowing endlessly in murky pools of ambiguity.  

2. Use scamps to convey the approach you will take.  
What’s a scamp? It’s the simplest way to convey an idea. Creative teams may generate dozens or hundreds of these, before sharing a subset with the client. They are usually drawings on pieces of paper which share the crux of an idea simply and with minimal production. Sharing these demonstrates a level of effort in the ideation phase, which clients often appreciate.  
How to apply in data science? Try outlining an experimental approach on a piece of paper, create something using example data and mock visuals, show your client what kind of output they can expect to see as a result of your work.  

3. Actually team up.  
The classic creative team is an art director and a writer. These folks often play other roles as well, like serious/funny or my personal favourite, good cop/bad cop.
Sharing your thinking immediately means you are anchoring in practicality and you must convince at least one other person why your idea is any good.  
The best teams will have differing but complementary skills. Data scientists come in so many different shapes that any two should have some skills which overlap, but also many more tips, tricks and experiences that aren’t common. No-knows everything. Use this variety to your advantage, don’t overthink it, just pair your data scientists up.  

4. Enforce constraints, stop and share early and often.  
Constraints are important in delivering work that is subjective. When is a painting ‘done’? When is a model ‘done’? The answer is always somewhere between ‘never’ and ‘right now’. If you are asking yourself the question, ‘should I stop now and share some progress’ the answer is probably yes!  
I’ve seen creative teams use a variety of techniques to enforce their own constraints, one of the best being a respectful relationship with a decent Creative Director and/or Creative Services Manager who helps the team stop spinning and deliver something incremental that moves the ball along the field.  

5. Celebrate.  
Creatives love their craft. Creative Directors insist to CEOs and CFOs that we send their teams to celebrate and socialise.  
I agree with them. Celebration and peer recognition is an important motivator, it helps raise the bar.   
As the roles of data practitioners mature, I see some opportunity for this to develop at an industry level. In the meantime, I suggest data science teams at the least do a show and tell with a broader cross-functional team, or anonymise their work (good practice itself) for presentation at a local Meetup.  

